name: gizi_check
description: "GiziCheck - A nutrition screening and food safety awareness app."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/foodsafety.png

  uses-material-design: true

  # Jika ingin menambahkan assets lain, tambahkan di sini
  # assets:
  #   - assets/images/your_image.png

  # Untuk font kustom, tambahkan di sini
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFont.ttf
